# Generated by Django 5.0.6 on 2024-06-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('report_name', models.CharField(max_length=100)),
                ('upload_files', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
