# Generated by Django 5.0.6 on 2024-06-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='Report',
        ),
    ]
